import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const formHtml = readFileSync("frontend/templates/cases/form.html", "utf8");
const reactFlowApp = readFileSync("frontend/static/ReactFlowApp.jsx", "utf8");

test("stage rows are not labeled or submitted as not-in-diagram records", () => {
  assert.equal(formHtml.includes("Chưa vào sơ đồ"), false);
  assert.equal(formHtml.includes("Trong sơ đồ"), false);
  assert.equal(formHtml.includes('querySelectorAll(\'#ocr-staging-area .ocr-staged-row[data-state="pending"]\')'), false);
});

test("restoring staging data does not force pool membership off", () => {
  const loadStagingMatch = formHtml.match(/loadStagingFromStorage\s*=\s*function\s*\(\)\s*{[\s\S]*?window\.loadStagingFromStorage\s*=\s*loadStagingFromStorage;/);
  assert.ok(loadStagingMatch, "loadStagingFromStorage block should exist");
  assert.equal(/inPool\s*:\s*false/.test(loadStagingMatch[0]), false);
});

test("removing from diagram clears stale tree state and returns the person to pool", () => {
  assert.match(
    reactFlowApp,
    /patch:\s*{\s*inDiagram:\s*false,\s*inTree:\s*false,\s*inPool:\s*true\s*}/
  );
  assert.match(
    formHtml,
    /setCustomerWorkflowState\(id,\s*{\s*inDiagram:\s*false,\s*inTree:\s*false,\s*inPool:\s*true\s*}\)/
  );
});

test("workflow restore guard allows explicit undelete from diagram removal", () => {
  assert.match(formHtml, /const\s+explicitUndelete\s*=/);
  assert.match(formHtml, /const\s+allowRevive\s*=/);
  assert.match(
    formHtml,
    /window\.__CUSTOMER_WORKFLOW__\[id\]\?\.deleted\s*&&\s*explicitUndelete\s*&&\s*!allowRevive\s*&&\s*!next\.inStaging[\s\S]*?next\.deleted\s*=\s*true;/
  );
  assert.match(
    formHtml,
    /window\.__CUSTOMER_WORKFLOW__\[id\]\?\.deleted\s*&&\s*!explicitUndelete\s*&&[\s\S]*?next\.inPool\s*=\s*false;/
  );
});

test("land owner action button is present and wired to the toggle handler", () => {
  assert.match(reactFlowApp, /onToggleLandOwner\?\.\(node\.id\)/);
  assert.match(reactFlowApp, /Chủ đất/);
  assert.equal(reactFlowApp.includes("S.landBadge"), false);
  assert.equal(reactFlowApp.includes(">★</span>"), false);
});

test("manual add sibling button is removed", () => {
  assert.equal(reactFlowApp.includes("+ Thêm Anh/Chị/Em"), false);
  assert.equal(reactFlowApp.includes("ghostAction: \"addSibling\""), false);
});

test("auto spouse and Z slots are generated in resolveSubRelations", () => {
  const resolveBlock = reactFlowApp.match(/function resolveSubRelations\(nodes,\s*shareMode\)\s*{[\s\S]*?return\s*\{\s*nodes:\s*finalNodes,/);
  assert.ok(resolveBlock, "resolveSubRelations should exist");
  assert.match(resolveBlock[0], /auto_spouse_/);
  assert.match(resolveBlock[0], /auto_z_/);
  assert.match(resolveBlock[0], /autoGenerated:\s*true/);
});

test("auto Z keeps one empty sibling slot after a Z has been assigned", () => {
  const resolveBlock = reactFlowApp.match(/function resolveSubRelations\(nodes,\s*shareMode\)\s*{[\s\S]*?return\s*\{\s*nodes:\s*finalNodes,/);
  assert.ok(resolveBlock, "resolveSubRelations should exist");
  assert.equal(resolveBlock[0].includes("if (existingZ) return;"), false);
  assert.match(resolveBlock[0], /nextAutoZSlotId/);
  assert.match(resolveBlock[0], /existingZCount/);
});

test("auto Z spare slots keep parent metadata and avoid assigned-node ids", () => {
  const resolveBlock = reactFlowApp.match(/function resolveSubRelations\(nodes,\s*shareMode\)\s*{[\s\S]*?return\s*\{\s*nodes:\s*finalNodes,/);
  assert.ok(resolveBlock, "resolveSubRelations should exist");
  assert.match(resolveBlock[0], /usedNodeIds/);
  assert.match(resolveBlock[0], /parentPersonId:\s*String\(node\.person\.id\)/);
  assert.match(resolveBlock[0], /parentSlotId:\s*node\.id/);
  assert.match(resolveBlock[0], /familyGroupId:\s*familyGroupFor\(node\)/);
});

test("createLogicalNode preserves auto slot metadata needed for drop materialization", () => {
  const createBlock = reactFlowApp.match(/function createLogicalNode\(overrides\)\s*{[\s\S]*?^\s*}/m);
  assert.ok(createBlock, "createLogicalNode should exist");
  assert.match(createBlock[0], /autoGenerated:\s*!!overrides\.autoGenerated/);
  assert.match(createBlock[0], /autoAnchorId:\s*overrides\.autoAnchorId/);
});

test("unchecking land owner removes auto-generated empty spouse slots", () => {
  const toggleBlock = reactFlowApp.match(/const onToggleLandOwner = useCallback\(\(nodeId\) => \{[\s\S]*?\},\s*\[commitLogicalNodes,\s*shareMode\]\);/);
  assert.ok(toggleBlock, "onToggleLandOwner should exist");
  assert.match(toggleBlock[0], /autoAnchorId/);
  assert.match(toggleBlock[0], /spouseOf/);
  assert.match(toggleBlock[0], /inPool:\s*true/);
});

test("commitAssign materializes auto slots into logicalNodes before assigning", () => {
  const commitBlock = reactFlowApp.match(/const commitAssign = useCallback\(\(nodeId,\s*rawPerson\) => \{[\s\S]*?\}, \[commitLogicalNodes, materializeGhostNode, nextId, shareMode\]\);/);
  assert.ok(commitBlock, "commitAssign should exist");
  assert.match(commitBlock[0], /autoGenerated/);
  assert.match(commitBlock[0], /baseNodes\s*=\s*\[\.\.\.prevNodes,/);
});

test("moveWithinDiagram materializes auto target slots before moving", () => {
  const moveBlock = reactFlowApp.match(/const moveWithinDiagram = useCallback\(\(sourceNodeId,\s*targetNodeId\) => \{[\s\S]*?\}, \[commitLogicalNodes, materializeGhostNode, nextId, pruneLinkedNodes, shareMode\]\);/);
  assert.ok(moveBlock, "moveWithinDiagram should exist");
  assert.match(moveBlock[0], /autoGenerated/);
});

test("childNodesOf includes fixed parent-child relationships for father/mother/spouse_parents", () => {
  const childBlock = reactFlowApp.match(/function childNodesOf\(parentNode\)\s*{[\s\S]*?return results;/);
  assert.ok(childBlock, "childNodesOf should exist");
  assert.match(childBlock[0], /spouse_father/);
  assert.match(childBlock[0], /spouse_mother/);
});

test("unchecking land owner clears fixed spouse of owner when no inflow, no dead child, and owner alive", () => {
  const toggleBlock = reactFlowApp.match(/const onToggleLandOwner = useCallback\(\(nodeId\) => \{[\s\S]*?\},\s*\[commitLogicalNodes,\s*shareMode\]\);/);
  assert.ok(toggleBlock, "onToggleLandOwner should exist");
  assert.match(toggleBlock[0], /node\.id === "owner"/);
  assert.match(toggleBlock[0], /fixedSpouse/);
  assert.match(toggleBlock[0], /anchorHasDeadChild/);
  assert.match(toggleBlock[0], /stillNeedsSpouse/);
});

test("land owner toggle recomputes spouse need from resolved engine state for the target anchor", () => {
  const toggleBlock = reactFlowApp.match(/const onToggleLandOwner = useCallback\(\(nodeId\) => \{[\s\S]*?\},\s*\[commitLogicalNodes,\s*shareMode\]\);/);
  assert.ok(toggleBlock, "onToggleLandOwner should exist");
  assert.match(toggleBlock[0], /resolveSubRelations\(nextNodes,\s*shareMode\)\.nodes/);
  assert.match(toggleBlock[0], /anchorAfterToggle/);
  assert.match(toggleBlock[0], /anchorAfterToggle\.inheritedShare/);
  assert.match(toggleBlock[0], /anchorAfterToggle\.finalShare/);
  assert.match(toggleBlock[0], /anchorPersonId/);
  assert.match(toggleBlock[0], /parentSlotId === nodeId/);
  assert.match(toggleBlock[0], /parentPersonId \|\| ""/);
});

test("owner spouse slot is hidden when no land owner, no dead-with-share, no dead child", () => {
  assert.match(reactFlowApp, /shouldShowOwnerSpouse/);
  assert.match(reactFlowApp, /n\.hidden/);
  assert.match(reactFlowApp, /n\.kind === "person" && !n\.hidden/);
});

test("empty parent slots are hidden until their anchor has a business reason", () => {
  const resolveBlock = reactFlowApp.match(/function resolveSubRelations\(nodes,\s*shareMode\)\s*{[\s\S]*?return\s*\{\s*nodes:\s*finalNodes,/);
  assert.ok(resolveBlock, "resolveSubRelations should exist");
  assert.match(resolveBlock[0], /shouldShowBirthParentSlots/);
  assert.match(resolveBlock[0], /shouldShowSpouseParentSlots/);
  assert.match(resolveBlock[0], /n\.id === "father" \|\| n\.id === "mother"/);
  assert.match(resolveBlock[0], /n\.id === "spouse_father" \|\| n\.id === "spouse_mother"/);
  assert.match(resolveBlock[0], /return \{ \.\.\.n, hidden: !shouldShowBirthParentSlots \}/);
  assert.match(resolveBlock[0], /return \{ \.\.\.n, hidden: !shouldShowSpouseParentSlots \}/);
});

test("case state is posted and hydrated so stage survives reload", () => {
  assert.match(formHtml, /name="case_state_json"\s+id="case-state-json"/);
  assert.match(formHtml, /window\.__INITIAL_CASE_STATE__/);
  assert.match(formHtml, /function collectCaseStateSnapshot\(/);
  assert.match(formHtml, /caseStateInput\.value\s*=\s*JSON\.stringify\(collectCaseStateSnapshot\(/);
  assert.match(formHtml, /hydrateStagingFromCaseState\(/);
});

test("ReactFlow app script version is bumped after dataflow fixes", () => {
  assert.match(formHtml, /ReactFlowApp\.jsx\?v=20260703b/);
});

test("OCR modal close does not stage or clear temporary OCR data", () => {
  const hiddenBlock = formHtml.match(/document\.getElementById\('ocrModal'\)\?\.addEventListener\('hidden\.bs\.modal'[\s\S]*?\n\s*\}\);/);
  assert.ok(hiddenBlock, "ocrModal hidden.bs.modal handler should exist");
  assert.equal(hiddenBlock[0].includes("autoStageOcrResults("), false);
  assert.equal(hiddenBlock[0].includes("ocrResults = []"), false);
  assert.equal(hiddenBlock[0].includes("imageQueue = []"), false);
});

test("AI OCR does not reset old working results before extracting more images", () => {
  const extractBlock = formHtml.match(/window\.ocrExtractAll\s*=\s*async function\s*\(\)\s*{[\s\S]*?document\.getElementById\('ocr-btn-text'\)\.innerHTML/);
  assert.ok(extractBlock, "ocrExtractAll block should exist");
  assert.equal(extractBlock[0].includes("resetOcrWorkingResults()"), false);
});

test("OCR modal has an explicit save button and no footer dismiss-only close button", () => {
  const ocrFooterBlock = formHtml.match(/<div class="modal-footer py-2 justify-content-between">[\s\S]*?<!--\s*\/Modal OCR/);
  assert.ok(ocrFooterBlock, "OCR modal footer block should exist");
  assert.match(ocrFooterBlock[0], /id="ocr-btn-save-results"/);
  assert.equal(ocrFooterBlock[0].includes('data-bs-dismiss="modal"'), false);
});

test("Phase 1 OCR modal does not expose a manual trash clear action", () => {
  assert.equal(formHtml.includes('onclick="ocrClearAll()"'), false);
  assert.equal(formHtml.includes("window.ocrClearAll = function"), false);
});

test("property OCR panel does not expose a trash clear button", () => {
  assert.equal(formHtml.includes('onclick="propertyOcrClearAll()"'), false);
  assert.equal(formHtml.includes('title="Xóa tất cả"'), false);
});

test("OCR staging allows missing-side and duplicate person rows", () => {
  const autoStageBlock = formHtml.match(/(?:async\s+)?function autoStageOcrResults\([^)]*\)\s*{[\s\S]*?\n\s*\}/);
  assert.ok(autoStageBlock, "autoStageOcrResults block should exist");
  assert.equal(autoStageBlock[0].includes("hasBlockingPersonWarnings("), false);
  assert.equal(autoStageBlock[0].includes("isDocAlreadyInCase("), false);
  assert.equal(autoStageBlock[0].includes("isDocAlreadyInStaging("), false);
});

test("OCR Luu can create a new stage row each time instead of updating a hidden link", () => {
  const autoStageStart = formHtml.indexOf("function autoStageOcrResults(options = {})");
  const autoStageEnd = formHtml.indexOf("function addToStagingLinked", autoStageStart);
  assert.ok(autoStageStart >= 0 && autoStageEnd > autoStageStart, "autoStageOcrResults block should exist");
  const autoStageBlock = formHtml.slice(autoStageStart, autoStageEnd);
  assert.equal(autoStageBlock.includes("&& !r._staged"), false);
  assert.equal(autoStageBlock.includes("r.type === 'person' && !r._staged"), false);
  assert.match(autoStageBlock, /window\.addToOcrStaging/);
  assert.match(autoStageBlock, /skipDuplicateGuard:\s*allowDuplicates/);
});

test("Local OCR control is not exposed in the current person OCR modal", () => {
  assert.equal(formHtml.includes("ocr-btn-extract-local"), false);
  assert.equal(formHtml.includes('onclick="ocrExtractLocal()"'), false);
});

test("OCR modal keeps queue inside the left upload column", () => {
  const modalBody = formHtml.match(/<div class="modal-body p-0 d-flex" style="min-height:60vh;">[\s\S]*?<\/div><!-- \/modal-body -->/);
  assert.ok(modalBody, "OCR modal body should exist");
  const body = modalBody[0];
  const queueIndex = body.indexOf('id="ocr-queue"');
  const rightColumnIndex = body.indexOf('id="ocr-results-panel"');
  assert.ok(queueIndex > 0, "OCR queue should be inside the modal body");
  assert.ok(rightColumnIndex > queueIndex, "OCR results panel should follow the queue");
  assert.equal(body.includes("ocr-btn-text-local"), false);
});

test("OCR result preview still maps result _files to retained imageQueue items", () => {
  assert.match(formHtml, /function findPreviewItemsForCard\(result,\s*data\)/);
  assert.match(formHtml, /Array\.isArray\(result\?\._files\)/);
  assert.match(formHtml, /Array\.isArray\(result\?\.data\?\._files\)/);
  assert.match(formHtml, /Array\.isArray\(result\?\._preview_items\)/);
  assert.match(formHtml, /Array\.isArray\(result\?\.data\?\._preview_items\)/);
  assert.match(formHtml, /imageQueue\.forEach\(\(item\)\s*=>/);
});

test("OCR person cards render visible source badges and queue statuses name QR vs OCR", () => {
  assert.match(formHtml, /class="ocr-src-badge"/);
  assert.match(formHtml, /if \(s === 'qr'\) return '[^']*QR/);
  assert.match(formHtml, /if \(s === 'ocr'\) return '[^']*OCR/);
  assert.match(formHtml, /if \(s === 'ai'\) return '[^']*OCR/);
});

test("stage commit button is named Cap nhat and is the only stage commit trigger", () => {
  const buttonBlock = formHtml.match(/<button[^>]+id="btn-save-participants"[\s\S]*?<\/button>/);
  assert.ok(buttonBlock, "stage commit button should exist");
  assert.match(buttonBlock[0], /Cap nhat/);
  assert.equal(buttonBlock[0].includes("Luu"), false);
  assert.match(formHtml, /window\.saveParticipantDraftRows\s*=\s*saveParticipantDraftRows/);
  assert.match(formHtml, /addEventListener\('click',\s*saveParticipantDraftRows\)/);
});

test("case submit does not auto-commit draft stage rows", () => {
  const submitBlock = formHtml.match(/document\.getElementById\('case-form'\)\?\.addEventListener\('submit'[\s\S]*?form\.submit\(\);/);
  assert.ok(submitBlock, "case submit handler should exist");
  assert.equal(submitBlock[0].includes("saveParticipantDraftRows("), false);
  assert.equal(submitBlock[0].includes("flushPendingDebounces("), false);
  assert.equal(submitBlock[0].includes("waitForPendingCustomerUpdates("), false);
});

test("case state snapshot serializes committed stage, not unsaved draft DOM", () => {
  const collectBlock = formHtml.match(/function collectCaseStateSnapshot\([^)]*\)\s*{[\s\S]*?^\s*}/m);
  assert.ok(collectBlock, "collectCaseStateSnapshot should exist");
  assert.match(formHtml, /function getCommittedStageSnapshot\(/);
  assert.match(collectBlock[0], /getCommittedStageSnapshot\(\)/);
  assert.equal(collectBlock[0].includes("querySelectorAll('#ocr-staging-area .ocr-staged-row')"), false);
});

test("stage inline edits stay draft until Cap nhat", () => {
  assert.equal(formHtml.includes("_queueDraftRowSave(row, record.id"), false);
  assert.equal(formHtml.includes("_queueDraftRowSave(row, row.dataset.cid"), false);
  assert.equal(formHtml.includes("setTimeout(() => _saveStagingRow(row"), false);
});

test("successful stage Cap nhat persists stage snapshot and then clears OCR temp", () => {
  const saveBlock = formHtml.match(/async function saveParticipantDraftRows\(options = \{\}\)\s*{[\s\S]*?return \{ savedCount, failedCount, rowCount: rows\.length \};/);
  assert.ok(saveBlock, "saveParticipantDraftRows should exist");
  assert.match(saveBlock[0], /persistCommittedStageSnapshot\(/);
  assert.match(saveBlock[0], /clearOcrTempAfterStageCommit\(\)/);
});

test("Stage date fields render in dd/mm/yyyy instead of leaking ISO dates", () => {
  assert.equal(formHtml.includes("ngay_chet.isoformat()"), false);
  assert.match(formHtml, /ngay_chet\.strftime\('%d\/%m\/%Y'\)/);
  assert.match(formHtml, /data-key="ngay_sinh" value="\$\{escVal\(_fmtDate\(record\.ngay_sinh\)\)\}" placeholder="dd\/mm\/yyyy"/);
  assert.match(formHtml, /data-key="ngay_chet" value="\$\{escVal\(_fmtDate\(record\.ngay_chet\)\)\}" placeholder="dd\/mm\/yyyy"/);
  assert.match(formHtml, /data-key="ngay_cap"\s+value="\$\{escVal\(_fmtDate\(record\.ngay_cap\)\)\}"\s+placeholder="dd\/mm\/yyyy"/);
});

test("React diagram removes people no longer present in committed stage", () => {
  const handlerStart = reactFlowApp.indexOf("const handleStagePersonsCommitted");
  const handlerEnd = reactFlowApp.indexOf('window.addEventListener("caseStagePersonsCommitted"', handlerStart);
  assert.ok(handlerStart >= 0 && handlerEnd > handlerStart, "caseStagePersonsCommitted handler should exist");
  const handlerBlock = reactFlowApp.slice(handlerStart, handlerEnd);
  assert.match(handlerBlock, /stageIds/);
  assert.match(handlerBlock, /removedIds/);
  assert.equal(handlerBlock.includes("if (!stageIds.size) return"), false);
  assert.match(handlerBlock, /collectRemovedPeople\(/);
  assert.match(handlerBlock, /pruneLinkedNodes\(/);
  assert.match(handlerBlock, /bridgeWorkflowUpdates\(/);
  assert.match(handlerBlock, /stageIds\.has\(String\(person\.id\)\)/);
});

test("pool is computed from committed stage minus diagram assignments", () => {
  const visibilityStart = formHtml.indexOf("function derivePoolVisibility(customerId)");
  const visibilityEnd = formHtml.indexOf("function getDiagramAssignedStageIds()");
  assert.ok(visibilityStart >= 0 && visibilityEnd > visibilityStart, "derivePoolVisibility block should exist");
  const visibilityBlock = formHtml.slice(visibilityStart, visibilityEnd);
  assert.match(visibilityBlock, /getCommittedStageSnapshot\(\)/);
  assert.match(visibilityBlock, /getDiagramAssignedStageIds\(\)/);
  assert.equal(visibilityBlock.includes("!!state.inPool"), false);
  assert.equal(visibilityBlock.includes("state.inPool"), false);
  assert.equal(visibilityBlock.includes("ensureCustomerWorkflow("), false);

  const loadPoolBlock = formHtml.match(/function loadPool\(\)\s*{[\s\S]*?^\s*}/m);
  assert.ok(loadPoolBlock, "loadPool should exist");
  assert.match(loadPoolBlock[0], /getPoolCandidateCustomerIds\(\)/);
  assert.equal(loadPoolBlock[0].includes("Object.keys(window.__CUSTOMER_REGISTRY__)"), false);
});

test("diagram save button is scoped to diagram state and closes its markup", () => {
  const buttonBlock = formHtml.match(/<button[^>]+data-action="\{\{ 'save-diagram' if obj else 'create-case' \}\}"[\s\S]*?<\/button>/);
  assert.ok(buttonBlock, "case action button should be a closed button element");
  assert.match(buttonBlock[0], /btn-submit-case/);
  assert.match(buttonBlock[0], /btn-create-case/);
  assert.match(buttonBlock[0], /Luu so do/);
  assert.match(buttonBlock[0], /Tao ho so/);
  assert.equal(buttonBlock[0].includes("LÆ°u há»“ sÆ¡"), false);
  assert.equal(buttonBlock[0].includes("LÆ°u thay Ä‘á»•i"), false);
});

test("diagram save posts diagram state without committing draft stage rows", () => {
  const submitBlock = formHtml.match(/document\.getElementById\('case-form'\)\?\.addEventListener\('submit'[\s\S]*?return;\s*\n\s*\}\);/);
  assert.ok(submitBlock, "case submit handler should exist");
  assert.match(submitBlock[0], /\/cases\/\$\{caseId\}\/diagram-update/);
  assert.equal(submitBlock[0].includes("persistCommittedStageSnapshot("), false);
  assert.equal(submitBlock[0].includes("collectDraftStageSnapshot("), false);
});

test("diagram removal cascades dependent branch people back to pool", () => {
  assert.match(reactFlowApp, /collectRemovedPeople\(logicalNodesRef\.current,\s*nodeId\)/);
  assert.match(reactFlowApp, /patch:\s*{\s*inDiagram:\s*false,\s*inTree:\s*false,\s*inPool:\s*true\s*}/);
  assert.match(reactFlowApp, /node\.id !== targetId && node\.parentSlotId && toRemove\.has\(node\.parentSlotId\)/);
});

test("diagram move prunes old dependent branch and only keeps moved person in diagram", () => {
  assert.match(reactFlowApp, /collectRemovedPeople\(logicalNodesRef\.current,\s*sourceNodeId\)/);
  assert.match(reactFlowApp, /const dependentPeople = affectedPeople\.filter\(\(person\) => String\(person\.id\) !== String\(sourcePerson\?\.id \|\| ""\)\)/);
  assert.match(reactFlowApp, /bridgeWorkflowUpdates\(dependentPeople\.map\(\(person\) => \(\{/);
  assert.match(reactFlowApp, /patch:\s*{\s*inDiagram:\s*false,\s*inTree:\s*false,\s*inPool:\s*true\s*}/);
});

test("import and manual add only create stage drafts before Cap nhat", () => {
  const importBlock = formHtml.match(/async function refreshPoolAfterImport\(\)\s*{[\s\S]*?^\s*}/m);
  assert.ok(importBlock, "refreshPoolAfterImport should exist");
  assert.match(importBlock[0], /window\.addToOcrStaging\(customer,\s*{\s*source:\s*'excel'/);
  assert.equal(importBlock[0].includes("commitCustomerToPool("), false);
  assert.equal(importBlock[0].includes("setCustomerWorkflowState("), false);
  assert.equal(importBlock[0].includes("updateCustomerWorkflow("), false);
  assert.equal(importBlock[0].includes("loadPool("), false);

  const inlineAddBlock = formHtml.match(/function addPersonEditRow\(\)\s*{[\s\S]*?^\s*}/m);
  assert.ok(inlineAddBlock, "addPersonEditRow should exist");
  assert.match(inlineAddBlock[0], /window\.addToOcrStaging\(\{\},\s*{\s*focusKey:\s*'ho_ten'\s*}\)/);
  assert.equal(inlineAddBlock[0].includes("commitCustomerToPool("), false);
  assert.equal(inlineAddBlock[0].includes("loadPool("), false);
});

test("pool search and registry fetch do not bypass committed stage", () => {
  const fetchBlock = formHtml.match(/async function fetchCustomersIntoRegistry\(query = '',\s*limit = 200\)\s*{[\s\S]*?return json\.data;\s*\n\s*}/);
  assert.ok(fetchBlock, "fetchCustomersIntoRegistry should exist");
  assert.equal(fetchBlock[0].includes("inPool: true"), false);
  assert.equal(fetchBlock[0].includes("setCustomerWorkflowState(record.id"), false);

  const searchClickBlock = formHtml.match(/poolSearchResults\.addEventListener\('click',\s*\(e\) => \{[\s\S]*?poolSearchInput\.value = '';\s*\n\s*\}\s*\n\s*\}\);/);
  assert.ok(searchClickBlock, "pool search click handler should exist");
  assert.match(searchClickBlock[0], /window\.addToOcrStaging\(toLegacyCustomerShape\(record\)/);
  assert.equal(searchClickBlock[0].includes("inPool: true"), false);
  assert.equal(searchClickBlock[0].includes("updateCustomerWorkflow(record.id"), false);
});

test("stage save never commits a just-saved customer directly to legacy pool", () => {
  const syncBlock = formHtml.match(/function _syncCustomerAfterSave\(raw,\s*options = \{\}\)\s*{[\s\S]*?return record;\s*\n\s*}/);
  assert.ok(syncBlock, "_syncCustomerAfterSave should exist");
  assert.equal(syncBlock[0].includes("commitCustomerToPool("), false);
  assert.match(syncBlock[0], /updateCustomerWorkflow\(record\.id,\s*{/);
});

test("legacy staged pool button is removed so only Cap nhat pushes stage to pool", () => {
  assert.equal(formHtml.includes("staged-pool-btn"), false);
  assert.equal(formHtml.includes("function addPersonRowToPool("), false);
  assert.equal(formHtml.includes("addPersonRowToPool = function"), false);
});

test("stage draft rows expose a direct remove button scoped to stage only", () => {
  assert.ok(formHtml.includes("stage-remove-btn"), "stage rows must have a remove button");
  assert.equal(formHtml.includes("staged-remove-btn"), false, "old staged-remove-btn class must not exist");
  assert.equal(formHtml.includes("DRAFT_ROW_REMOVED"), false, "no legacy DRAFT_ROW_REMOVED event");
  assert.equal(formHtml.includes('title="XÃ³a khi workflow"'), false);
  assert.equal(formHtml.includes('title="XÃ³a khi danh sÃ¡ch"'), false);
  assert.equal(formHtml.includes('title="XoÃ¡ khi danh sÃ¡ch"'), false);
});

test("legacy tree and pool workflow updates do not clear stage membership directly", () => {
  const putBackBlock = formHtml.match(/putDataBackToPool = function \(data,\s*force = false,\s*originalCard = null\) \{[\s\S]*?\n\s*\};/);
  assert.ok(putBackBlock, "putDataBackToPool should exist");
  assert.equal(putBackBlock[0].includes("inStaging: false"), false);

  const buildPersonCardBlock = formHtml.match(/function buildPersonCard\(data,\s*role,\s*withShare = true,\s*shareVal = '0',\s*receiveVal = '1'\) \{[\s\S]*?\n\s*\}/);
  assert.ok(buildPersonCardBlock, "buildPersonCard should exist");
  assert.equal(buildPersonCardBlock[0].includes("inStaging: false"), false);

  const hydrateLegacyTreeBlock = formHtml.match(/const delayedSpouses = \[\];[\s\S]*?delayedGrand\.forEach\(\(\{ data, share, receive \}\) => \{[\s\S]*?\n\s*\}\);/);
  assert.ok(hydrateLegacyTreeBlock, "legacy participant hydration block should exist");
  assert.equal(hydrateLegacyTreeBlock[0].includes("inStaging: false"), false);
});

test("only stage commit marks workflow records as deleted", () => {
  const deletedTrueMatches = formHtml.match(/deleted:\s*true/g) || [];
  assert.equal(deletedTrueMatches.length, 1);
  assert.equal(reactFlowApp.includes("deleted: true"), false);

  const persistBlock = formHtml.match(/async function persistCommittedStageSnapshot\(options = \{\}\)\s*{[\s\S]*?return \{ stage, removedIds \};/);
  assert.ok(persistBlock, "persistCommittedStageSnapshot should exist");
  assert.match(persistBlock[0], /removedIds\.forEach/);
  assert.match(persistBlock[0], /deleted:\s*true/);
  assert.match(persistBlock[0], /__allowClearStaging:\s*true/);
});

test("only stage flows can revive deleted records", () => {
  const nonStageBlocks = [
    reactFlowApp.match(/const removeWithWorkflow = useCallback\(\(nodeId\) => \{[\s\S]*?\}, \[onRemove\]\);/),
    reactFlowApp.match(/const moveWithinDiagram = useCallback\(\(sourceNodeId,\s*targetNodeId\) => \{[\s\S]*?\}, \[commitLogicalNodes, materializeGhostNode, nextId, pruneLinkedNodes, shareMode\]\);/),
    reactFlowApp.match(/const commitAssign = useCallback\(\(nodeId,\s*rawPerson\) => \{[\s\S]*?\}, \[commitLogicalNodes, materializeGhostNode, nextId, shareMode\]\);/),
    formHtml.match(/putDataBackToPool = function \(data,\s*force = false,\s*originalCard = null\) \{[\s\S]*?\n\s*\};/),
    formHtml.match(/function buildPersonCard\(data,\s*role,\s*withShare = true,\s*shareVal = '0',\s*receiveVal = '1'\) \{[\s\S]*?\n\s*\}/),
    formHtml.match(/const delayedSpouses = \[\];[\s\S]*?delayedGrand\.forEach\(\(\{ data, share, receive \}\) => \{[\s\S]*?\n\s*\}\);/),
  ];
  nonStageBlocks.forEach((block) => {
    assert.ok(block, "non-stage block should exist");
    assert.equal(block[0].includes("deleted: false"), false);
  });

  const stageReviveMatches = formHtml.match(/deleted:\s*false[\s\S]{0,120}inStaging:\s*true/g) || [];
  assert.ok(stageReviveMatches.length >= 4, "expected multiple stage-scoped revive patches");
});

test("new case diagram save is blocked instead of full form submit fallback", () => {
  const submitBlock = formHtml.match(/document\.getElementById\('case-form'\)\?\.addEventListener\('submit'[\s\S]*?return;\s*\n\s*\}\);/);
  assert.ok(submitBlock, "case submit handler should exist");
  assert.match(submitBlock[0], /if\s*\(!caseId\)\s*{/);
  assert.equal(/if\s*\(!caseId\)\s*{\s*form\.submit\(\);/.test(submitBlock[0]), false);
  assert.match(submitBlock[0], /showToast\([^)]*Tao ho so/);
});

test("diagram assignment blocks occupied targets instead of replace or swap", () => {
  const validateBlock = reactFlowApp.match(/function validateAssignment\(logicalNodes,\s*nodeId,\s*person,\s*targetNodes = logicalNodes\)\s*{[\s\S]*?^\s*}/m);
  assert.ok(validateBlock, "validateAssignment should exist");
  assert.match(validateBlock[0], /targetNode\.person/);
  assert.match(validateBlock[0], /Ô này đã có ngườ|đã có ngườ|occupied/i);

  const commitBlock = reactFlowApp.match(/const commitAssign = useCallback\(\(nodeId,\s*rawPerson\) => \{[\s\S]*?\}, \[commitLogicalNodes, materializeGhostNode, nextId, shareMode\]\);/);
  assert.ok(commitBlock, "commitAssign should exist");
  assert.equal(commitBlock[0].includes("const preview = assignPersonToNode(currentNodes"), false);
});

test("diagram move does not swap with occupied target", () => {
  const moveBlock = reactFlowApp.match(/const moveWithinDiagram = useCallback\(\(sourceNodeId,\s*targetNodeId\) => \{[\s\S]*?\}, \[commitLogicalNodes, materializeGhostNode, nextId, pruneLinkedNodes, shareMode\]\);/);
  assert.ok(moveBlock, "moveWithinDiagram should exist");
  assert.equal(moveBlock[0].includes("targetPerson"), false);
  assert.equal(moveBlock[0].includes("buildAssignedNode(node, baseNodes, targetPerson)"), false);
  assert.match(moveBlock[0], /window\.alert/);
});

test("diagram hydrate skips hidden or deleted saved nodes on reload", () => {
  const hydrateBlock = reactFlowApp.match(/function hydrateEngineStateNodes\(\)\s*{[\s\S]*?return ensureSpareChildNode\(nodes\);\s*}/);
  assert.ok(hydrateBlock, "hydrateEngineStateNodes should exist");
  assert.match(hydrateBlock[0], /saved\.hidden\s*\|\|\s*saved\.deleted/);
  assert.match(hydrateBlock[0], /filter\(\(node\)\s*=>\s*Boolean\(node\)\)/);
});

test("diagram reload keeps flowFrom metadata through hydrate and next engine save", () => {
  const hydrateBlock = reactFlowApp.match(/function hydrateEngineStateNodes\(\)\s*{[\s\S]*?return ensureSpareChildNode\(nodes\);\s*}/);
  assert.ok(hydrateBlock, "hydrateEngineStateNodes should exist");
  assert.match(hydrateBlock[0], /flowFrom:/);
  assert.match(hydrateBlock[0], /saved\.flowFrom/);

  const buildInputBlock = reactFlowApp.match(/function buildEngineInput\(models\)\s*{[\s\S]*?return\s*{\s*people,/);
  assert.ok(buildInputBlock, "buildEngineInput should exist");
  assert.match(buildInputBlock[0], /flowFrom:/);
  assert.match(buildInputBlock[0], /node\.flowFrom/);

  const engineRunBlock = reactFlowApp.match(/function runDiagramEngine\(models\)\s*{[\s\S]*?return\s*{\s*nodes:\s*applyEngineResult\(models,\s*engineResult\),[\s\S]*?};\s*}/);
  assert.ok(engineRunBlock, "runDiagramEngine should exist");
  assert.match(engineRunBlock[0], /flowFrom:\s*node\.flowFrom/);
});

test("diagram reload keeps slot metadata bucket/allowsShare/removable through next engine save", () => {
  const buildInputBlock = reactFlowApp.match(/function buildEngineInput\(models\)\s*{[\s\S]*?return\s*{\s*people,/);
  assert.ok(buildInputBlock, "buildEngineInput should exist");
  assert.match(buildInputBlock[0], /bucket:\s*node\.bucket/);
  assert.match(buildInputBlock[0], /allowsShare:\s*node\.allowsShare/);
  assert.match(buildInputBlock[0], /removable:\s*node\.removable/);

  const engineRunBlock = reactFlowApp.match(/function runDiagramEngine\(models\)\s*{[\s\S]*?return\s*{\s*nodes:\s*applyEngineResult\(models,\s*engineResult\),[\s\S]*?};\s*}/);
  assert.ok(engineRunBlock, "runDiagramEngine should exist");
  assert.match(engineRunBlock[0], /bucket:\s*node\.bucket/);
  assert.match(engineRunBlock[0], /allowsShare:\s*node\.allowsShare/);
  assert.match(engineRunBlock[0], /removable:\s*node\.removable/);
});

test("diagram fallback engine-missing path still persists engineState nodes for reload", () => {
  const engineRunBlock = reactFlowApp.match(/function runDiagramEngine\(models\)\s*{[\s\S]*?return\s*{\s*nodes:\s*applyEngineResult\(models,\s*engineResult\),[\s\S]*?};\s*}/);
  assert.ok(engineRunBlock, "runDiagramEngine should exist");
  assert.match(engineRunBlock[0], /const\s+engineInput\s*=\s*buildEngineInput\(models\)/);
  const missingBranch = engineRunBlock[0].match(/if\s*\(!inheritanceEngine\?\.runInheritanceCase\)\s*{[\s\S]*?return\s*{[\s\S]*?};\s*\n\s*}/);
  assert.ok(missingBranch, "engine missing branch should exist");
  assert.match(missingBranch[0], /engineState:\s*{\s*schemaVersion:\s*1,[\s\S]*nodes:\s*persistedNodes/);
});

test("runDiagramEngine has a single engine-missing fallback branch", () => {
  const engineRunBlock = reactFlowApp.match(/function runDiagramEngine\(models\)\s*{[\s\S]*?return\s*{\s*nodes:\s*applyEngineResult\(models,\s*engineResult\),[\s\S]*?};\s*}/);
  assert.ok(engineRunBlock, "runDiagramEngine should exist");
  const missingMatches = engineRunBlock[0].match(/if\s*\(!inheritanceEngine\?\.runInheritanceCase\)\s*{/g) || [];
  assert.equal(missingMatches.length, 1);
});

test("diagram save persists structural person slots, not only occupied people", () => {
  const engineRunBlock = reactFlowApp.match(/function runDiagramEngine\(models\)\s*{[\s\S]*?return\s*{\s*nodes:\s*applyEngineResult\(models,\s*engineResult\),[\s\S]*?};\s*}/);
  assert.ok(engineRunBlock, "runDiagramEngine should exist");
  assert.match(engineRunBlock[0], /const\s+persistedNodes\s*=\s*models[\s\S]*?\.filter\(\(node\)\s*=>\s*node\.kind\s*===\s*"person"\)/);
  assert.equal(engineRunBlock[0].includes("nodes: engineInput.nodes.map("), false);
});

test("diagram engine-missing warning text is not mojibake", () => {
  const engineRunBlock = reactFlowApp.match(/function runDiagramEngine\(models\)\s*{[\s\S]*?return\s*{\s*nodes:\s*applyEngineResult\(models,\s*engineResult\),[\s\S]*?};\s*}/);
  assert.ok(engineRunBlock, "runDiagramEngine should exist");
  assert.match(engineRunBlock[0], /message:\s*"Chua tai duoc inheritance_engine\.js\."/);
});
